channels:
  - conda-forge
  - ets
dependencies:
  - python=3.6
  - pip
  - numpy
  - nltk
  - cchardet
  - crfpp==0.59
  - coveralls
  - skll==2.0
  - jinja2
  - scikits-bootstrap
  - nose
  - coverage
  - pip:
    - python-zpar
